[render]
section_order = ["security", "removal", "feature", "fix", "misc"]
insert_after = "<!--- -->"

[vcs]
protected = ["master"]

[type.security]
name = "Security"

[type.removal]
name = "Removals and Deprecations"

[type.feature]
name = "Features"

[type.fix]
name = "Bug Fixes"

[type.misc]
name = "Internal Changes"
