on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          # Our MSRV
          - 1.56.0
          # Anymore MSRV
          - 1.86.0
          - stable
        features:
          # std
          - ""
          # std + hashbrown
          - "--features hashbrown"
          # std + anymore
          - "--features anymore"
          # std + hashbrown + anymore
          - "--all-features"
          # no_std
          - "--no-default-features"
          # no_std + hashbrown
          - "--no-default-features --features hashbrown"
          # no_std + anymore
          - "--no-default-features --features anymore"
          # no_std + hashbrown + anymore
          - "--no-default-features --features hashbrown,anymore"
        exclude:
          # Anymore won't run on 1.56.0
          - toolchain: 1.56.0
            features: "--features anymore"
          - toolchain: 1.56.0
            features: "--all-features"
          - toolchain: 1.56.0
            features: "--no-default-features --features anymore"
          - toolchain: 1.56.0
            features: "--no-default-features --features hashbrown,anymore"
    steps:
      - uses: actions/checkout@v4
      - uses: "dtolnay/rust-toolchain@master"
        with:
          toolchain: "${{ matrix.toolchain }}"
      - uses: Swatinem/rust-cache@v2
      - run: "cargo test ${{ matrix.features }}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: "-D warnings"
