on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.36.0
          - stable
        features:
          # std
          - ""
          # std + hashbrown
          - "--all-features"
          # no_std
          - "--no-default-features"
          # no_std + hashbrown
          - "--no-default-features --features hashbrown"
    steps:
      - uses: actions/checkout@v4
      - uses: "dtolnay/rust-toolchain@master"
        with:
          toolchain: "${{ matrix.toolchain }}"
      - uses: Swatinem/rust-cache@v2
      - run: "cargo test ${{ matrix.features }}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: "-D warnings"
